#define ENCODER_A_PINS { B2 }
#define ENCODER_B_PINS { B3 }
#define ENCODER_DIRECTION_FLIP
#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 60000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 15
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define DYNAMIC_KEYMAP_MACRO_COUNT 36
#define WS2812_DI_PIN F7